sudo: required
dist: xenial
language: python
env:
  global:
    - VERSION=1.${TRAVIS_BUILD_NUMBER}
  matrix:
    - ARCH=rpi
      GOIMG=resin/rpi-raspbian
      DOCKER_BUILD=mastermindg/docker-flow-proxy:rpi-${VERSION}
      DOCKERFILE=test.Dockerfile
services:
  - xvfb # X virtual framebuffer. Run the graphical application without display them while also having the ability to take screenshots.
  - docker
script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # build image
  - docker build --tag t_system_test -f test.Dockerfile
  # push image
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
#      docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
#      docker tag hypriot/rpi-raspbian
      docker push t_system_test
    fi
notifications:
  on_success: change
  on_failure: change  # `always` will be the setting once code changes slow down
